# Generated by Django 6.0.1 on 2026-02-03 01:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'departamentos',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_empleado',
            field=models.CharField(default='0000', help_text='ID de empleado de 4 digitos', max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='el numero de empleado debe tener 4 digitos', regex='^\\d{4}')]),
        ),
        migrations.CreateModel(
            name='sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('departamentos', models.ManyToManyField(help_text='Departamentos en esta sede', related_name='sedes', to='users.departamento')),
            ],
        ),
    ]
