# Generated by Django 6.0.1 on 2026-02-03 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_departamento_usuario_sede'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='numero_empleado',
            new_name='ID_empleado',
        ),
    ]
