# Generated by Django 6.0.1 on 2026-02-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_numero_empleado_usuario_id_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='codigo',
            field=models.CharField(default='CCS', help_text='Codigo de sede de 3 caracteres', max_length=3, unique=True),
            preserve_default=False,
        ),
    ]
