# Generated by Django 6.0.1 on 2026-02-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_sede_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
