# Generated by Django 6.0.1 on 2026-02-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_sede_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(max_length=3, null=True, unique=True),
        ),
    ]
