# Generated by Django 6.0.1 on 2026-02-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_departamento_codigo_alter_sede_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(default='DEPT', max_length=3, unique=True),
        ),
    ]
