# Generated by Django 6.0.1 on 2026-02-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_departamento_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(default='DEPT', max_length=10, unique=True),
        ),
    ]
