# Generated by Django 6.0.1 on 2026-02-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_departamento_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(default='DEPT', max_length=10),
        ),
    ]
