# Generated by Django 6.0.1 on 2026-02-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_departamento_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='codigo',
        ),
    ]
