# Generated by Django 6.0.1 on 2026-02-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_departamento_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
