# Generated by Django 6.0.1 on 2026-02-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_tiempo_resolucion_horas_matriz_prioridad_tiempo_resolucion_minutos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='usuario',
            field=models.ForeignKey(
                blank=True,
                db_column='usuario',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='tickets_asignados',
                to='users.usuario',
                to_field='ID_empleado',
            ),
        ),
    ]
