# Generated by Django 6.0.1 on 2026-02-11 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_sede_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='activos_categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categorias de activo',
            },
        ),
        migrations.CreateModel(
            name='activos',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(db_column='departamento', on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='users.departamento', to_field='nombre')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='users.sede', to_field='codigo')),
                ('usuario_asignado', models.ForeignKey(blank=True, db_column='usuario_asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_asignados', to=settings.AUTH_USER_MODEL, to_field='ID_empleado')),
                ('categoria', models.ForeignKey(db_column='categoria', on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='inventory.activos_categoria', to_field='nombre')),
            ],
        ),
    ]
