# Generated by Django 6.0.1 on 2026-02-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos',
            name='codigo',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
