# Generated by Django 6.0.1 on 2026-02-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_activos_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activos_categoria',
            name='codigo',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
