# Generated by Django 6.0.1 on 2026-02-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_activos_categoria_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos',
            name='codigo',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activos_categoria',
            name='codigo',
            field=models.CharField(default='TYPE', max_length=10, unique=True),
        ),
    ]
