# Generated by Django 6.0.1 on 2026-02-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_activos_categoria_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos_categoria',
            name='codigo',
            field=models.CharField(default='TYPE', max_length=10, unique=True),
        ),
    ]
