# Generated by Django 6.0.1 on 2026-02-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_activos_categoria_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activos_categoria',
            name='codigo',
        ),
    ]
