# Generated by Django 6.0.1 on 2026-02-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_activos_categoria_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activos_categoria',
            name='categoria',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
