# Generated by Django 6.0.1 on 2026-02-15 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_activos_categoria_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activos_categoria',
            old_name='categoria',
            new_name='codigo',
        ),
    ]
