# Generated by Django 6.0.1 on 2026-02-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_categoria_activos_categoria_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos_categoria',
            name='codigo',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
