# Generated by Django 6.0.1 on 2026-05-01 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_activos_categoria_codigo'),
        ('users', '0015_alter_departamento_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='users.sede', to_field='nombre'),
        ),
    ]
