# Generated by Django 6.0.1 on 2026-05-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_activos_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos',
            name='serial',
            field=models.CharField(max_length=50),
        ),
    ]
