# Generated by Django 6.0.1 on 2026-05-01 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_activos_sede'),
        ('users', '0015_alter_departamento_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos',
            name='departamento',
            field=models.ForeignKey(db_column='departamento', on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='users.departamento', to_field='codigo'),
        ),
    ]
