# Generated by Django 6.0.1 on 2026-02-11 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='matriz_prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(max_length=20, unique=True)),
                ('tiempo_respuesta_horas', models.IntegerField()),
                ('tiempo_resolucion_horas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ticket', models.CharField(max_length=30, unique=True)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('activo_afectado', models.ForeignKey(db_column='activo_afectado', limit_choices_to={'estado': 'Activo'}, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_afectados', to='inventory.activos')),
                ('prioridad', models.ForeignKey(db_column='prioridad', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.matriz_prioridad', to_field='prioridad')),
                ('solicitante', models.ForeignKey(db_column='solicitante', on_delete=django.db.models.deletion.PROTECT, related_name='tickets_solicitados', to=settings.AUTH_USER_MODEL, to_field='ID_empleado')),
                ('usuario', models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.PROTECT, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL, to_field='ID_empleado')),
            ],
        ),
        migrations.CreateModel(
            name='tickets_comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='tickets_adjuntos/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, db_column='autor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_autor', to=settings.AUTH_USER_MODEL, to_field='ID_empleado')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tickets.tickets')),
            ],
        ),
        migrations.CreateModel(
            name='tickets_historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=30)),
                ('estado_nuevo', models.CharField(max_length=30)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(db_column='responsable', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='ID_empleado', verbose_name='Responsable del cambio')),
                ('ticket_id', models.ForeignKey(db_column='ticket_id', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tickets.tickets', to_field='codigo_ticket')),
            ],
        ),
    ]
