# Generated by Django 6.0.1 on 2026-02-17 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_activos_categoria_codigo'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matriz_prioridad',
            old_name='tiempo_resolucion_horas',
            new_name='tiempo_resolucion_minutos',
        ),
        migrations.RenameField(
            model_name='matriz_prioridad',
            old_name='tiempo_respuesta_horas',
            new_name='tiempo_respuesta_minutos',
        ),
        migrations.AlterField(
            model_name='tickets',
            name='activo_afectado',
            field=models.ForeignKey(db_column='activo_afectado', limit_choices_to={'estado': 'activo'}, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_afectados', to='inventory.activos'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='prioridad',
            field=models.ForeignKey(db_column='prioridad', default='Media', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.matriz_prioridad', to_field='prioridad'),
        ),
    ]
