# Generated by Django 6.0.1 on 2026-02-18 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_tiempo_resolucion_horas_matriz_prioridad_tiempo_resolucion_minutos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='prioridad',
            field=models.ForeignKey(db_column='prioridad', default='N/A', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.matriz_prioridad', to_field='prioridad'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='usuario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL, to_field='ID_empleado'),
        ),
    ]
