# Generated by Django 6.0.1 on 2026-02-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_tickets_estado_alter_tickets_prioridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Resuelto', 'Resuelto'), ('Cerrado', 'Cerrado')], default='Pendiente', max_length=30),
        ),
    ]
