# Generated by Django 6.0.1 on 2026-02-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_tickets_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets_comentarios',
            old_name='ticket_id',
            new_name='ticket',
        ),
    ]
